import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The docs sidebar is autogenerated from the folder structure under docs/.
// Ordering and category labels are driven by each folder's _category_.json
// and by the `sidebar_position` front matter on individual pages.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
